apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-fluentd.conf
    @INCLUDE filter-k8s-log-level.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-nest-field.conf
    @INCLUDE filter-rename-field.conf
    @INCLUDE filter-kubelet-log-level.conf
    @INCLUDE filter-exclude.conf
    @INCLUDE filter-remove-field.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/kube*.log,/var/log/containers/fluent*.log,/var/log/containers/kibana*.log,/var/log/containers/nginx-ingress*.log,/var/log/containers/calico*.log,/var/log/containers/charts*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Buffer_Chunk_Size 10MB
        Buffer_Max_Size   10MB

    [INPUT]
        Name              systemd
        Tag               kubelet
        Path              /var/log/journal
        DB                /var/log/kubelet.db
        Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail    true

  filter-k8s-log-level.conf: |
    [FILTER]
        Name parser
        Match kube.*
        Key_Name  log
        Parser    loglevel
        Reserve_Data True

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  filter-exclude.conf: |
    [FILTER]
        Name           grep
        Match          *
        Exclude        message kube-probe
        Exclude        message ghost
        Exclude        message HEAD
        Exclude        message /api/v1/cainfo
        Exclude        message /metrics
        Exclude        message 200 0
        Exclude        message 302 \d+
        Exclude        message fs.go:418
        Exclude        message kubelet_node_status
        Exclude        message PRETTY_NAME
    
  filter-rename-field.conf: |
    [FILTER]
      Name modify
      Match kubelet
      Rename _SYSTEMD_UNIT service_name
      Rename _HOSTNAME k8s:host
      Rename MESSAGE message
      Add k8s:app devops

    [FILTER]
      Name modify
      Match kube.*
      Rename log message
      Add level info
    
  filter-kubelet-log-level.conf: |
    [FILTER]
      Name parser
      Match kubelet
      Key_Name  message
      Parser    loglevel
      Reserve_Data True
  filter-nest-field.conf: |
    [FILTER]
      Name nest
      Match kube.*
      Operation lift
      Nested_under kubernetes
      Prefix_with k8s:
    
    [FILTER]
      Name nest
      Match kube.*
      Operation lift
      Nested_under k8s:labels
      Prefix_with k8s:
    
    
  filter-remove-field.conf: |
    [FILTER]
      Name record_modifier
      Match kube.*
      Remove_key stream
      Remove_key time
    
    [FILTER]
      Name record_modifier
      Match kubelet
      Whitelist_key service_name
      Whitelist_key k8s:host
      Whitelist_key k8s:app
      Whitelist_key message
      Whitelist_key level
    
    [FILTER]
      Name record_modifier
      Match kube.*
      Whitelist_key k8s:host
      Whitelist_key k8s:pod_name
      Whitelist_key k8s:namespace_name
      Whitelist_key k8s:container_name
      Whitelist_key k8s:host
      Whitelist_key k8s:app
      Whitelist_key message
      Whitelist_key level

  output-fluentd.conf: |
    [OUTPUT]
        Name                forward
        Match               *
        Host                your-fluentd-centralize
        Port                24224
        Retry_Limit         False
        tls                 off
        tls.verify          off

  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As   escaped    log    do_next
        Decode_Field_As   json       log
    
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

